-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."softcartDimDate"
(
    dateid integer NOT NULL,
    date date,
    day integer,
    weekday integer,
    weekdayname character varying(9),
    month integer,
    monthname character varying(9),
    year integer,
    quarter integer,
    quartername character varying(2),
    PRIMARY KEY (dateid)
);

CREATE TABLE public."softcartDimCategory"
(
    categoryid integer NOT NULL,
    category character varying(25),
    PRIMARY KEY (categoryid)
);

CREATE TABLE public."softcartDimItem"
(
    itemid integer NOT NULL,
    item character varying(25),
    PRIMARY KEY (itemid)
);

CREATE TABLE public."softcartDimCountry"
(
    countryid integer NOT NULL,
    country character varying(25),
    PRIMARY KEY (countryid)
);

CREATE TABLE public."softcartFactSales"
(
    orderid integer NOT NULL,
    dateid integer,
    categoryid integer,
    itemid integer,
    countryid integer,
    price numeric(10, 2),
    PRIMARY KEY (orderid)
);

ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (dateid)
    REFERENCES public."softcartDimDate" (dateid)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (categoryid)
    REFERENCES public."softcartDimCategory" (categoryid)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (itemid)
    REFERENCES public."softcartDimItem" (itemid)
    NOT VALID;


ALTER TABLE public."softcartFactSales"
    ADD FOREIGN KEY (countryid)
    REFERENCES public."softcartDimCountry" (countryid)
    NOT VALID;

END;
